default:
    controller: main
    action: home

login:
    controller: user
    action: login

logout:
    controller: user
    action: logout

register:
    controller: user
    action: register

dashboard:
    controller: admin
    action: home

mail:
    controller: mail
    action: main

confirmaccount:
    controller: user
    action: confirmAccount